// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAf07o5tPUyZvEYwgp8D7eV1twr1aIFK3k',
    appId: '1:817800606883:web:0d1ae4aa2770de92997b16',
    messagingSenderId: '817800606883',
    projectId: 'loginregister-89d7a',
    authDomain: 'loginregister-89d7a.firebaseapp.com',
    storageBucket: 'loginregister-89d7a.appspot.com',
    measurementId: 'G-BFCV2B6KCM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCzSgX4hjIYRH9OYFmWp0E8XoBIaxUREog',
    appId: '1:817800606883:android:c7eae95c6afddafa997b16',
    messagingSenderId: '817800606883',
    projectId: 'loginregister-89d7a',
    storageBucket: 'loginregister-89d7a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCwzqF2Vh71vaCjpPcvYjRtpQKKMlhJkBg',
    appId: '1:817800606883:ios:e19668924453cb2d997b16',
    messagingSenderId: '817800606883',
    projectId: 'loginregister-89d7a',
    storageBucket: 'loginregister-89d7a.appspot.com',
    iosClientId: '817800606883-rfjfs9b034hjbduqhn9r9ifuj15m2h04.apps.googleusercontent.com',
    iosBundleId: 'com.example.project',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCwzqF2Vh71vaCjpPcvYjRtpQKKMlhJkBg',
    appId: '1:817800606883:ios:b299ebe431e0f525997b16',
    messagingSenderId: '817800606883',
    projectId: 'loginregister-89d7a',
    storageBucket: 'loginregister-89d7a.appspot.com',
    iosClientId: '817800606883-5iprep93u29o3tnhkje17cnf5ehonj5f.apps.googleusercontent.com',
    iosBundleId: 'com.example.project.RunnerTests',
  );
}
